### ISSUE TITLE
[?format=text] No newlines around headings

### ISSUE THREAD

**Issue by DarkCat09** [TxtDot/txtdot#100]
**Example**: [MDN page](https://txt.dc09.ru/get?url=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FJavaScript%2FReference%2FGlobal_Objects%2FArray%2Ffind&engine=&format=text)

- When parser output format set to text, I often get headings concatenated with a paragraph body:

#### 1
`Try itSyntaxfind(callbackFn)`  
`find(callbackFn, thisArg)`

#### 2
`SpecificationsSpecificationECMAScript Language Specification # sec-array.prototype.findBrowser compatibilityBCD tables only load in the browserSee also`

- While it must be:

#### 1
![txtdot1](https://github.com/TxtDot/txtdot/assets/50486086/f1a9207c-713a-4040-9de7-0babc5426e8b)

#### 2
![txtdot2](https://github.com/TxtDot/txtdot/assets/50486086/ccdbb601-edc0-4f1b-ae83-2a776a02ee35)

**Comment by DarkCat09** [comment]
Readability's bug?

**Comment by artegoser** [comment]
We can create custom HTML to text formatter like this https://www.npmjs.com/package/html-to-text
