### ISSUE TITLE
ARM architecture

### ISSUE THREAD

**Issue by uGeek** [TxtDot/txtdot#161]
I have tried installing the service on my Raspberry Pi and ARM64 VPS server, but it does not work because it is not multi-architecture. Are you planning to implement ARM architecture?

**Comment by DarkCat09** [comment]
> but it does not work

@uGeek, provide more detailed information, please.

**Comment by uGeek** [comment]
I have tried to install the service on a Raspberry Pi with ARM architecture, but Docker says it is only compatible with AMD64 architecture.

Are you planning to implement ARM architecture?

```
! txtdot The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

I tried the demo, and it's an amazing service. Thank you very much!

**Comment by artegoser** [comment]
Thanks, we will try to add a multi-architecture in the next release

**Comment by uGeek** [comment]
Thank you

**Comment by uGeek** [comment]
I have done a Docker build after installing Docker-buildx to create an image from my Raspberry Pi and it has built the image and is working perfectly. So, there is no incompatibility with any libraries due to the architecture. Simply, it needs to be made multi-architecture and everything should work fine.

**Comment by artegoser** [comment]
Done in v1.9.0

**Comment by DarkCat09** [comment]
After adding multi-arch build:

```
$ sudo docker pull ghcr.io/txtdot/txtdot:latest
latest: Pulling from txtdot/txtdot
manifest unknown
```

Same for tags `1.9.0` and `main`

**Comment by artegoser** [comment]
this is due to an incorrect GitHub action that was deleting related to the main multi-arch image images

**Comment by uGeek** [comment]
But.... On ARM what tag should be used?

**Comment by artegoser** [comment]
:v1.9.0 corrupted, now use :main

**Comment by artegoser** [comment]
now you can use v1.9.1

**Comment by uGeek** [comment]
Thanks a lot! It works excellent. I understand that in the next latest version it will already be there, is that correct?
