### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by DarkCat09** [TxtDot/txtdot#31]
Plugins are divided into different types:

- [x] Engines (#146) - allow you to create custom engines to process sites by domain and routes
- [x] Middlewares (#159) - They add the ability to process output of engines. For example, you can add a syntax highlighter or add navigation to sites. 

Plugins code (in typescript) is located in [plugins](https://github.com/TxtDot/txtdot/tree/main/packages/plugins) package. They're published in `@txtdot` npm organization.

To activate a plugin, the instance admin have to install it with npm and then add to plugins list in `pluginConfig.ts`

**Comment by artegoser** [comment]
Maybe later.

**Comment by artegoser** [comment]
First create a separate txtdot-sdk library. And add creation of custom engines.
