### ISSUE TITLE
Parsing JS apps

### ISSUE THREAD

**Issue by DarkCat09** [TxtDot/txtdot#49]
Execute scripts that are not related to analytics/ads in [isolated-vm](https://github.com/laverdet/isolated-vm) passing JSDOM object to their context, and only after that process DOM with Readability / anything else.

Should be configurable, `EXEC_JS=false|true` in .env, false by default.

Can be implemented as a separate engine named "readability with js".

**Comment by DarkCat09** [comment]
- #54  
DOM object can not be passed into isolated-vm context, even when copying all properties recursively, [see MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#things_that_dont_work_with_structured_clone).

- #55  
JSDOM VM context always gives "TypeError: cannot read properties of undefined", looks like there are some APIs that are not implemented in JSDOM.

***

### I give up

**Comment by artegoser** [comment]
Actually this works with webder now
