### ISSUE TITLE
Huge HTML hangs whole server

### ISSUE THREAD

**Issue by DarkCat09** [TxtDot/txtdot#67]
**Example:** https://www.win.tue.nl/~aeb/natlang/ie/tochB.html

This page is really big, so okay, txtdot proxy can't parse it in reasonable time. But it hangs the whole server, and after client gets timeout error, txtdot still does not accept any requests, what makes DoS attacks as simple as possible: attacker needs only one request.

Using NodeJS profiler, I found out that JSDOM takes almost all the time.

What we can do:
- Set a timeout for server response, so Fastify won't wait page processing to complete; [connectionTimeout](https://fastify.dev/docs/latest/Reference/Server/#connectiontimeout) seems to be the solution, but I'm not sure.
- Switch to other HTML processing library which provides DOM API (sorted by last commit date: [linkedom](https://github.com/WebReflection/linkedom), [happy-dom](https://github.com/capricorn86/happy-dom), [cheerio](https://github.com/cheeriojs/cheerio)).
- Rewrite Readability so it won't need DOM API; and/or rewrite it in Rust.

**Comment by artegoser** [comment]
actually there is a problem with this function
![image](https://github.com/TxtDot/txtdot/assets/59178854/2524affb-e466-470d-9d65-eb8dfd589d22)

**Comment by artegoser** [comment]
We should probably get rid of dom and do it on the regex. I removed the code where the links change and the server responds and doesn't hang.
